[build-system]
requires = ["setuptools", "wheel", "torch"]
build-backend = "setuptools.build_meta"

[project]
name = "DCNv2"
version = "0.1.0"
description = "Deformable Convolutional Networks v2"
dependencies = ["torch", "numpy"]
